#! /bin/bash

CUR_PWD=$PWD

statsd_home="$( dirname "$( cd "$( dirname "$0" )" && pwd )")"

cd $statsd_home

npm install
npm install -g forever
npm install -g forever-service

forever-service install takipi-statsd --script $statsd_home/statsd -o "$statsd_home/config.js"

cd $CUR_PWD
